### ISSUE TITLE
Add ability to manage programs with audio descrpitions

### ISSUE THREAD

**Issue by falcon03** [nightflyer73/plugin.video.raitv#12]
RAI offers a variety of its programs with audio descriptions for blind people. The page that shows them is

http://www.rai.tv/dl/RaiTV/programmi/page/Page-09f11f27-027c-4140-a208-ab910d028583.html

Could you add support for them in the addon, please? A lot of italian blind people could benefit from this.

**Comment by nightflyer73** [comment]
They are already supported:
Programmi On Demand -> Cerca un programma -> segretariato -> Segretariato Sociale
Programmi On Demand -> Elenco programmi -> S -> Segretariato Sociale
