### ISSUE TITLE
[Info] rai channel stream url

### ISSUE THREAD

**Issue by gborri** [nightflyer73/plugin.video.raitv#14]
I have tried to look for your email but I've not chance to find it.

I would like to use this software in order to stream channel to tvheadend and then to kodi.
could you help me to get it work? i need to find url for every channel. I've tried to read you code but have no chance to found a solution.

https://github.com/Jalle19/node-ffmpeg-mpegts-proxy

thanks
Giovanni

**Comment by nightflyer73** [comment]
You should look in resources/lib/stations.py and in relinker.py.

**Comment by gborri** [comment]
@nightflyer73 is this the link of Rai 1? 

http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2621467&output=47. 

it's in http://www.rai.tv/dl/RaiTV/iphone/android/smartphone/advertising_config.html response.

**Comment by nightflyer73** [comment]
No. You have to know how the relinker works. Read relinker.py.

**Comment by HalowTV** [comment]
hey mate how I can contact you @nightflyer73
