### ISSUE TITLE
Channels working through website, but not through addon

### ISSUE THREAD

**Issue by vincentporretta** [nightflyer73/plugin.video.raitv#15]
Hi,
I'm using the add-on in Canada with airvpn (which allows rai.tv content through). I can watch all RAI channels via the rai.tv website, but unfortunately they aren't playing in Kodi with the add-on (only the international channel opens).  In my Kodi log and it indicates that it's returning my location as ESTERO.  I'm not sure why the streams would play through rai.tv, but not through the add-on.  Any thoughts?  Thanks for all of your work on making a great add-on!
Best,
VJ

**Comment by nightflyer73** [comment]
The fact that you can watch live streaming channels via rai.tv website is irrelevant. The plugin works differently - it is more similar to the android app.

The fact that you can see that location is ESTERO means that you're abroad and your VPN is not working correctly. 

Moreover some streams are now protected HLS streams (with AES-128). It seems Kodi can't play these streams on most systems. This is a report made by a user:
http://forum.kodi.tv/showthread.php?tid=155922&pid=2365705#pid2365705

Anyway I live in Italy and I can only support Italian users.
