### ISSUE TITLE
Adapt plugin to new raiplay api

### ISSUE THREAD

**Issue by el3kim** [nightflyer73/plugin.video.raitv#16]
si riesce ad aggiornare?

**Comment by nightflyer73** [comment]
Mi spieghi cosa dovrei aggiornare? Mi sembra che il plugin, a parte qualche problema noto, funzioni correttamente.

**Comment by el3kim** [comment]
La Rai ha aggiunto una nuova stagione ad un posto al sole 2016-2017 che non
risulta ancora nel plug-ins.

Il 15/Set/2016 09:57, "nightflyer73" <notifications@github.com> ha scritto:

**Comment by nightflyer73** [comment]
E' cambiata la maggior parte delle API. Il lavoro di reverse engineering e di adattamento sarà lungo.

**Comment by Leo-C** [comment]
Ciao,
anche se le API sono in buona parte cambiate, le vecchie ancora funzionano, ed in particolare ora tutti i canali RAI sono disponibili in RAI Play (= RAI Replay + Guida TV @ http://www.raiplay.it/guidatv/ ), anche se alcuni canali non mostrano contenuti recuperabili (es. RAI Storia), ma altri prima non utilizzabili mostrano i contenuti visualizzabili (es. RAI Movie). In particolare questi compaiono nel JSON scaricato da stations.py ( http://www.rai.it/dl/RaiTV/iphone/android/smartphone/advertising_config.html ), ma non compaiono in Kody.

Grazie mille per quanto potrai fare.

Leonardo

**Comment by el3kim** [comment]
è fattibile l'aggiornamento?

**Comment by tsdx** [comment]
Anche la stagione 2016-2017 di "Report" non viene visualizzata, mentre rimangono fruibili gli anni passati.

**Comment by someuser94** [comment]
Se puo' essere utile a questo indirizzo: http://www.raiplay.it/dl/RaiTV/RaiPlayMobile/Prod/Config/programmiAZ-elenco.json e' possibile trovare tutti i programmi che la rai ha in streaming e seguondo i percorsi json si puo' arrivare ai relativi link per lo streaming

**Comment by Leo-C** [comment]
Ciao,
non mi spiego un piccolo problema.
Su Kodi nell'elenco dei canali Rai Replay (popolato dalla funzione `show_replay_channels()` in `default.py`) non compaiono molti canali (es. Rai Movie), pur essendo letti dalla lista tv_stations ottenuta in `get_tv_stations()` in `stations.py` che popola pure le Dirette TV, in cui pero' compaiono.

Ti ringrazio per qualunque chiarimento possa essermi utile

Leonardo

**Comment by nightflyer73** [comment]
Leo-C stai usando una vecchia versione di questo addon.

**Comment by Leo-C** [comment]
Ho controllato su Kodi, e uso la versione 1.0.13, ch credo essere l'ultima.
Devo forse reinstallarla?

Leonardo

**Comment by nightflyer73** [comment]
Leo-C, questo non è un forum di supporto. E' un bug report sul lavoro di adattamento dell'addon alle api di raiplay. La versione a cui mi riferisco è quella che si trova in questo repository.

**Comment by Leo-C** [comment]
OK, e' corretto, e mi dispiace di non aver controllato prima il disallineamento con il repository Kodi.

Poiche' pero' effettui tu tale aggiornamento, se vuoi sposto la domanda su tale tema al [forum ](http://forum.kodi.tv/showthread.php?tid=155922) di competenza

Grazie

Leonardo

**Comment by angel-27** [comment]
@nightflyer73 .
Ciao, volevo tenerti a conoscenza di una stranezza che casualmente ho scoperto e che probabilmente può' esserti d'aiuto per un'eventuale soluzione. Come sicuramente sai i canali Rai 1, Rai 2, e Rai 3 del tuo plugin  non funzionano ma ho scoperto che dopo una pulizia della cache e subito dopo un riavvio del sistema FUNZIONANO anche se solo per una volta. Infatti se ad esempio dopo la pulizia e il riavvio vado nelle "DIRETTE" e quindi "Rai 1" il canale parte in un'attimo e si vede che e' uno spettacolo,  pero' se passo su un'altro canale (esempio Rai 2) e poi ritorno su "Rai 1" quest'ultimo non funziona più, per cui per rimetterlo in funzione devo rifare la pulizia e riavviare il sistema.
Non sono un genio di python ma credo che forse con piccole modifiche potrebbero funzionare tutti i canali alla grande (sparo una castroneria, inibire la cache del plugin?).
Nei miei test ho utilizzato il plugin "RAI ON DEMAND" scaricato da qui, mentre per la pulizia della cache ho utilizzato il plugin "RAW MAINTENANCE".
Spero di aver fatto cosa gradita  scrivendo qui e spero altre si' che si arrivi presto ad una soluzione per risolvere presto i problemi che affliggono questo fantastico plugin.
Angelo

**Comment by someuser94** [comment]
Ho sviluppato un plugin/addon che funziona con il nuovo servizio raiplay se @nightflyer73 e' d'accordo provo ad includerlo nel suo addon. La ricerca viene effettuata soltanto sui titoli inseriti nel file json pubblicato sul sito

**Comment by nightflyer73** [comment]
@someuser94: non è sufficiente usare il file JSON che hai citato sopra. Bisogna partire dal valore di  menuService in http://www.raiplay.it/mobile/prod/config/RaiPlay_Config.json. Comunque un occhiata al tuo codice la darei volentieri.

**Comment by someuser94** [comment]
Quel file di configurazione non lo avevo proprio visto :). In questo weekend penso di riuscire ad integrarlo e poi vediamo un po' se ne vale la pena o meno

**Comment by someuser94** [comment]
Ho applicato le modifiche sul mio fork. Chiunque lo voglia provare basta che lo scarichi e sostituisca il contenuto di quello esistente. Le modifiche al codice originale sono veramente minime

**Comment by tsdx** [comment]
@someuser94: sul fork le dirette vanno, ma non c'e' alcun contenuto nei programmi ondemand.

**Comment by someuser94** [comment]
@tsdx: io ho aggiunto una nuova voce di menu' RaiRepaly, la trovi subito prima del cerca e dopo il "Da non perdere"
![cattura2](https://cloud.githubusercontent.com/assets/20421682/21079917/083a3e86-bfa1-11e6-887a-5df9043516e8.PNG)

**Comment by tsdx** [comment]
@someuser94: 

- su linux+kodi, dirette ok, non vedo la nuova voce raireplay e niente ondemand, 

- su openelec,  dirette ok, niente nuova voce e ondemand ok, con errore sulla stagione 2016-17 di  report. Mentre e' ok la stagione passata di report.

**Comment by nightflyer73** [comment]
@tsdx considerato che il codice degli streaming non è stato cambiato nel fork, possiamo finirla qui? Grazie.

**Comment by someuser94** [comment]
@tsdx devi scaricare questo file https://github.com/someuser94/plugin.video.raitv/archive/master.zip e copiarne tutto il contenuto nella cartella esistente dell'addon. Come ti ha detto nightflyer non e' stato cambiato il codice dello streaming e quindi l'on demand continuera' a non funzionare

**Comment by tsdx** [comment]
ciao,
il tuo fork lavora egregiamente.

Nn so come contattarti quindi ne  approfitto qui.
kodi mi sta appassionando.
Volevo sistemare su kodi l'addon "lacosa".
Volevo farlo costruendo da zero un nuovo addon video. Puoi indicarmi 
qualcosa dove poter apprendere le basi?
Non so programmare ed e' una grossa pecca, ma con dei semplici wget sono 
arrivato al link dei video.

tsdx@box /tmp $ wget -O archivio.html http://www.la-cosa.it
--2016-12-18 18:59:31--  http://www.la-cosa.it/
Connessione a 127.0.0.1:8118... connesso.
Richiesta Proxy inviata, in attesa di risposta... 200 OK
Lunghezza: 73097 (71K) [text/html]
Salvataggio in: "archivio.html"

100%[============================================================================================================================================================>] 
73.097      --.-K/s   in 0s

2016-12-18 18:59:31 (234 MB/s) - "archivio.html" salvato [73097/73097]

tsdx@box /tmp $ wget -O link1.html 
http://www.la-cosa.it/2016/12/04/beppe-grillo-la-canta-ai-politici-e-ai-segretari-di-partito-ma-con-che-faccia-vi-presentata-davanti-ai-giovani/
--2016-12-18 19:00:18-- 
http://www.la-cosa.it/2016/12/04/beppe-grillo-la-canta-ai-politici-e-ai-segretari-di-partito-ma-con-che-faccia-vi-presentata-davanti-ai-giovani/
Connessione a 127.0.0.1:8118... connesso.
Richiesta Proxy inviata, in attesa di risposta... 200 OK
Lunghezza: 214914 (210K) [text/html]
Salvataggio in: "link1.html"

100%[============================================================================================================================================================>] 
214.914     --.-K/s   in 0,001s

2016-12-18 19:00:20 (204 MB/s) - "link1.html" salvato [214914/214914]

tsdx@box /tmp $ wget -O link2.html 
http://www.chickybox.com/embed/beppe-grillo-la-canta-ai-politici-e-ai-segretari-di-partito-ma-con-che-faccia-vi-presentata-davanti-ai-giovani-tha3rOLVYr
--2016-12-18 19:00:37-- 
http://www.chickybox.com/embed/beppe-grillo-la-canta-ai-politici-e-ai-segretari-di-partito-ma-con-che-faccia-vi-presentata-davanti-ai-giovani-tha3rOLVYr
Connessione a 127.0.0.1:8118... connesso.
Richiesta Proxy inviata, in attesa di risposta... 200 OK
Lunghezza: 4539 (4,4K) [text/html]
Salvataggio in: "link2.html"

100%[============================================================================================================================================================>] 
4.539       --.-K/s   in 0s

2016-12-18 19:00:37 (189 MB/s) - "link2.html" salvato [4539/4539]

tsdx@box /tmp $ wget -O videotrovato.webm 
http://video.mainstreaming.tv/delivery/55010f9a-25af-4d6e-888b-7beb9d429d98-vp8_240_320_340000_ogg_48017.webm
--2016-12-18 19:01:04-- 
http://video.mainstreaming.tv/delivery/55010f9a-25af-4d6e-888b-7beb9d429d98-vp8_240_320_340000_ogg_48017.webm
Connessione a 127.0.0.1:8118... connesso.
Richiesta Proxy inviata, in attesa di risposta... 302 Found
Posizione: 
http://a5cdn.mainstreaming.tv/delivery/55010f9a-25af-4d6e-888b-7beb9d429d98-vp8_240_320_340000_ogg_48017.webm 
[segue]
--2016-12-18 19:01:05-- 
http://a5cdn.mainstreaming.tv/delivery/55010f9a-25af-4d6e-888b-7beb9d429d98-vp8_240_320_340000_ogg_48017.webm
Connessione a 127.0.0.1:8118... connesso.
Richiesta Proxy inviata, in attesa di risposta... 200 OK
Lunghezza: 2450224 (2,3M) [video/webm]
Salvataggio in: "infami.webm"

100%[============================================================================================================================================================>] 
2.450.224    698KB/s   in 3,4s

2016-12-18 19:01:08 (698 KB/s) - "videotrovato.webm" salvato 
[2450224/2450224]

tsdx@box /tmp $


A me basterebbe costruire  un menu semplice e farlo titolare a kodi.

in allegato ho messo le pagine scaricate ed ho evitato di mettere il 
video per non appesantire la mail.
Grazie per la tua pazienza! :)


Il 11/12/2016 17:31, someuser94 ha scritto:
> @tsdx devi scaricare questo file https://github.com/someuser94/plugin.video.raitv/archive/master.zip e copiarne tutto il contenuto nella cartella esistente dell'addon. Come ti ha detto nightflyer non e' stato cambiato il codice dello streaming e quindi l'on demand continuera' a non funzionare
>
