### ISSUE TITLE
Diretta rai

### ISSUE THREAD

**Issue by Albe46** [nightflyer73/plugin.video.raitv#18]
Come mai la diretta TV di RAI1 RAI2 e RAI3 sono interdetto, hai i sorgenti o il file m3u di queste dirette ?

**Comment by nightflyer73** [comment]
Some live streams are protected HLS streams (with AES-128). It seems Kodi can't play these streams, at least not on all supported platform.

A user sent this report:
http://forums.kodi.tv/showthread.php?tid=155922&pid=2365705#pid2365705

Anyway, it's not an addon issue. Closing.
