### ISSUE TITLE
Replay also today shows

### ISSUE THREAD

**Issue by 24mu13** [nightflyer73/plugin.video.raitv#19]
In the new Rai Play platform, you can re-play also shows of the same day.
Could you check if possible also through the API?

**Comment by nightflyer73** [comment]
The replay section already lists today's programmes per channel. Please check before opening bug reports!

**Comment by 24mu13** [comment]
To me, doesn't, using 1.0.13 version.

![image](https://cloud.githubusercontent.com/assets/14576296/20889536/a9330824-bb03-11e6-97c8-375b4403ab67.png)

Complimenti per il lavoro con questi plugin, e grazie per la sua cortesia e disponibilità.

**Comment by nightflyer73** [comment]
Have you tried the version in this repository???

**Comment by 24mu13** [comment]
True, you're right: from this repo works fine! Thank you.

If I may suggest, I would:
- Increase the version to 1.0.14 or whatever, just to avoid confusion
- Upload  the latest version to the official Kodi repo

Again, congratulation for the good job.

**Comment by nightflyer73** [comment]
When I finish to update the addon to the new raiplay API I'll release a new version and submit it to the official Kodi repo. 

Keep in mind this is just one man's work and done in my really small free time. Patches are always welcome :)
