### ISSUE TITLE
no video with Aeon MQ7 skin

### ISSUE THREAD

**Issue by mjnman** [nightflyer73/plugin.video.raitv#21]
From a few days I can't see any video on channels but audio work. I removed the plugin, directory and package on .kodi path and reinstalled from kodi repository but the problem it's the same.
With confluence default skin the plugin work correctly but with Aeon MQ7 I can't see the video.
In attachment the sceenshot.
The others plugins or streaming TV working correctly. I.e. Video Mediaset or La7 on demand I can see the video.
![raireplay_novideo](https://cloud.githubusercontent.com/assets/8179167/23800133/6a2ce3b4-05ab-11e7-82ca-459fb95895e4.png)

**Comment by nightflyer73** [comment]
I'm sorry but I don't think the problem is in this addon. It doesn't require a particular skin, and kodi plays the stream (not the addon!).

**Comment by mjnman** [comment]
it's a strange behaviour because the plugin doesn't work from favorites or menu of video -> add-on menu but if I start correctly from settings -> add-ons -> My add-ons -> Video add-ons -> RAI ON DEMAND. I can see correctly the video in m3u8.

**Comment by nightflyer73** [comment]
To further analyse this issue I need a way to reproduce it. So please write the exact steps and provide a corresponding log file.

**Comment by nightflyer73** [comment]
BTW, can you also report OS, Kodi and addon versions?

**Comment by mjnman** [comment]
I'm using Kodi 16 Jarvis, debian 7 jessie and raitv with last master from git.
You can install AEON MQ7 from "https://drive.google.com/drive/folders/0BxZQqz5XxlaDcFNSd0pZanl2TFU" and...
DOESN'T WORK:
go on Video or Audio -> add-on -> rai on demand select channel.
LOGS:
08:53:06 T:140684837259008  NOTICE: RAI geolocation: IT
08:53:10 T:140684837259008  NOTICE: Playing...
08:53:10 T:140684837259008  NOTICE: Relinker URL: http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=746966
08:53:10 T:140684837259008  NOTICE: Media URL: http://raiquattro1hls-lh.akamaihd.net/i/raiquattro1_1@335025/master.m3u8?hdnea=st=1489737191~exp=1489737341~acl=/*~hmac=1e5be6b87d1cd1796c73db5074d78e4f2848240eb2a6bd467b6f4cbd51eb8a27
08:53:10 T:140686369433600  NOTICE: CDVDPlayer::CloseFile()
08:53:10 T:140686369433600  NOTICE: DVDPlayer: waiting for threads to exit
08:53:10 T:140684846962432  NOTICE: CDVDPlayer::OnExit()
08:53:10 T:140684846962432  NOTICE: Closing stream player 1
08:53:10 T:140684846962432  NOTICE: Waiting for audio thread to exit
08:53:10 T:140684873189120  NOTICE: thread end: CDVDPlayerAudio::OnExit()
08:53:10 T:140684846962432  NOTICE: Closing audio device
08:53:10 T:140684846962432  NOTICE: Deleting audio codec
08:53:10 T:140684846962432  NOTICE: Closing stream player 2
08:53:10 T:140684846962432  NOTICE: waiting for video thread to exit
08:53:10 T:140684933687040  NOTICE: thread end: video_thread
08:53:10 T:140684846962432  NOTICE: deleting video codec
08:53:10 T:140686369433600  NOTICE: DVDPlayer: finished waiting
08:53:10 T:140686369433600  NOTICE: CDVDPlayer::CloseFile()
08:53:10 T:140686369433600  NOTICE: DVDPlayer: waiting for threads to exit
08:53:10 T:140686369433600  NOTICE: DVDPlayer: finished waiting

WORK:
settings -> add-ons -> My add-ons -> Video add-ons -> RAI ON DEMAND -> Open I can see correctly the video in m3u8.
LOGS:
08:45:01 T:140716390594304  NOTICE: RAI geolocation: IT
08:45:04 T:140716390594304  NOTICE: Playing...
08:45:04 T:140716390594304  NOTICE: Relinker URL: http://mediapolisevent.rai.it/relinker/relinkerServlet.htm?cont=2606803
08:45:04 T:140716390594304  NOTICE: Media URL: http://raiuno1hls-lh.akamaihd.net/i/raiuno1_1@37570/master.m3u8?hdnea=st=1489736664~exp=1489736814~acl=/*~hmac=745b8a6d75e91dc9baf7668e5354bc98ed16ecc1e76ffc348805d852bb1bf0f4
08:45:04 T:140718085101568  NOTICE: DVDPlayer: Opening: http://raiuno1hls-lh.akamaihd.net/i/raiuno1_1@37570/master.m3u8?hdnea=st=1489736664~exp=1489736814~acl=/*~hmac=745b8a6d75e91dc9baf7668e5354bc98ed16ecc1e76ffc348805d852bb1bf0f4|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F57.0.2956.0+Safari%2F537.36
08:45:04 T:140718085101568 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
08:45:04 T:140717105272576  NOTICE: Creating InputStream
08:45:04 T:140717105272576  NOTICE: Creating Demuxer
08:45:04 T:140717105272576  NOTICE: Opening stream: 0 source: 256
08:45:04 T:140717105272576  NOTICE: Creating video codec with codec id: 28
08:45:04 T:140717105272576  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
08:45:04 T:140717105272576  NOTICE: Creating video thread
08:45:04 T:140717105272576  NOTICE: Opening stream: 1 source: 256
08:45:04 T:140717105272576  NOTICE: Finding audio codec for: 86018
08:45:04 T:140717105272576  NOTICE: Creating audio thread
08:45:04 T:140716580652800  NOTICE: running thread: CDVDPlayerAudio::Process()
08:45:04 T:140716570425088  NOTICE: running thread: video_thread
08:45:04 T:140716570425088  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating VDPAU(928x522)
08:45:04 T:140716570425088  NOTICE: VDPAU::Open: required extension GL_NV_vdpau_interop not found
08:45:04 T:140716570425088  NOTICE:  (VDPAU) Close
08:45:04 T:140716570425088  NOTICE: VAAPI::Close
08:45:04 T:140716580652800  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
08:45:04 T:140716580652800  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 4 packets of duration 23
08:45:04 T:140716570425088  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
08:45:04 T:140716570425088  NOTICE:  fps: 25.000000, pwidth: 928, pheight: 522, dwidth: 928, dheight: 522
08:45:04 T:140716570425088  NOTICE: Display resolution DESKTOP : 800x600@ 60.00 - Full Screen (16)
08:45:04 T:140718085101568  NOTICE: Using GL_TEXTURE_2D
08:45:04 T:140718085101568  NOTICE: GL: Selecting Single Pass YUV 2 RGB shader
08:45:04 T:140718085101568  NOTICE: GL: NPOT texture support detected
08:45:04 T:140718085101568  NOTICE: GL: Using GL_ARB_pixel_buffer_object
08:45:05 T:140717515089664  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 199 ms

**Comment by mjnman** [comment]
Closed because I don't enough time to test.
