### ISSUE TITLE
localizeUrl returns http status 404 when abroad

### ISSUE THREAD

**Issue by passani** [nightflyer73/plugin.video.raitv#22]
...as of April 6 2016

**Comment by nightflyer73** [comment]
Do you live abroad?

**Comment by passani** [comment]
Si, caro

**Comment by nightflyer73** [comment]
It's an upstream issue with this URL:
http://mediapolisgs.rai.it/relinker/relinkerServlet.htm?cont=201342

If you are abroad you'll get http status 404.

I'll make a workaround.

**Comment by passani** [comment]
Grazie Nightflyer. I am getting:
type Status report
message /relinker/ESTERO
description The requested resource (/relinker/ESTERO) is not available.

Are you saying that Rai added extra geofencing? Anyway this sucks because I am paying the Canone in italy!

**Comment by nightflyer73** [comment]
> Are you saying that Rai added extra geofencing? Anyway this sucks because I am paying the Canone in italy!

No. I believe it's just an upstream bug.

Anyway most RAI programmes are geo-blocked. So you won't be able to watch them abroad.

**Comment by passani** [comment]
I use a VPN when I want live TV, but because of time difference, it doesn't make a lot of difference. Up to a few days ago, I was able to watch most on-demand without VPN (news, Che tempo che fa, nemo nessuno escluso, and RaiNews24 live) which was really nice (RaiInternational is a pathetic channel meant for the oriundi who still like albano e romina)

**Comment by fenix-soft** [comment]
In the forum kodi, have solved this way:

http://forum.kodi.tv/showthread.php?tid=155922&pid=2564822#pid2564822

I hope nightflyer73 update the script or at least tell her about to change manually the country to italy variable for it to work abroad as it did before the changes in version 2.0 script

**Comment by nightflyer73** [comment]
@fenix-soft the proposed solution isn't the proper way to solve this issue.

**Comment by passani** [comment]
Hey Nightflyer, are you sure that my problem is that I am abroad. I tried going through a VPN with Italy and the problem seems to be exactly the same.
Also, how do I test your change? I understand that Addons should update automatically, but this hasn't been the case for me. I know enough Python to modify the code myself if you can provide a pointer to where the addons can be found on my local file system. Thanks

**Comment by passani** [comment]
Forget that. I downloaded the plugin directly from here as a ZIP file and I was able to install from Zip.
It sort of works. Rai Replay works. Telegiornalis seem to no longer be accessible though.

Grazie comunque per questo addon.

**Comment by nightflyer73** [comment]
> Also, how do I test your change? I understand that Addons should update automatically, but this hasn't been the case for me.

The addon is automatically updated if I submit an update to the official kodi addon repository.

> I know enough Python to modify the code myself if you can provide a pointer to where the addons can be found on my local file system. Thanks

It really depends on the OS you are using. Have a look at kodi wiki to find out the correct location.

> Forget that. I downloaded the plugin directly from here as a ZIP file and I was able to install from Zip.

It works but you won't get automatic updates any more because the paths are no longer correct.

> It sort of works. Rai Replay works. Telegiornalis seem to no longer be accessible though.

Every feature based on getLastContentByTag and getMostVisited is currently broken. It seems that upstream returns invalid links. Right now I lack time to further analyze this. This is why I still haven't submitted an updated to the official kodi repository.

**Comment by vladi1971** [comment]
Luca...I am having the same issues....gli stessi problemi with Rai on Deman?  were you able to get a fix?  this is driving me crazy

**Comment by vladi1971** [comment]
I tried to change as suggested (see file/pic attached)....still not working
![rai problem](https://cloud.githubusercontent.com/assets/27759750/25169209/0950ab2a-249b-11e7-84c8-e98a83463952.png)

**Comment by nightflyer73** [comment]
The correct patch is the one in the commit 211345b0effad2ce88f9dce0cc4328e269a9d0af as reported above. You can already use the version in this repository to fix the issue.

**Comment by vladi1971** [comment]
I would know how to change …..I am new to Kodi…and especially changing codes/etc.

 

How can I do it?

 

Would you be ok to “ENTER”      my computer remotely while I am present and make necessary updates?   

 

Let me know.

 

ciao

**Comment by passani** [comment]
Go to the top of root of this GitHub preject and download the whiole thing as a ZIP tarball (a zipball?).

Start Kodi, disinstall Rai on Demand, and re-install it from ZIP file by selecting, you guessed it, the Zipball.

**Comment by vladi1971** [comment]
Grazie….I will try….thanks so MUCHOOOO

**Comment by bladerunner82** [comment]
@nightflyer73 will there be a update in the official kodi repo ?

**Comment by nightflyer73** [comment]
@bladerunner82 you should really re-read my answers in this thread.

**Comment by vladi1971** [comment]
It worked.  Went to to download the zip

However, before I used to to see the news from "archivio telegiornali".  Now, it seems that you have to go to the third option called "REPLAY'...and from there chose any program you would like to see.
Thanks again Nightflyer73 and Luca Passani for the instructions.
![20170424_224308](https://cloud.githubusercontent.com/assets/27759750/25370752/9f69fc92-2941-11e7-80c0-82354422d898.jpg)
![20170424_224250](https://cloud.githubusercontent.com/assets/27759750/25370753/9f6cc828-2941-11e7-882d-6a25b56bd386.jpg)

**Comment by nightflyer73** [comment]
@vladi1971 you should really re-read my answers in this thread too. Anyway, you are free to open a specific issue since it's not related to this one.
