### ISSUE TITLE
Check log

### ISSUE THREAD

**Issue by Chiaramonte1981** [nightflyer73/plugin.video.raitv#23]
I've tried on 17.1 and 16.1 Kodi. Spmc 16.3 and 16.6. No luck having Rai on demand opening since yesterday. Is the add on dead?

**Comment by nightflyer73** [comment]
I have no problem. Please provide a log file.

**Comment by Chiaramonte1981** [comment]
How do I get the log.  Everytime I try to open the add on it wont

**Comment by Chiaramonte1981** [comment]
Can I email you a screen shot of the log. I can't copy and paste it and email upload fails Everytime

**Comment by Chiaramonte1981** [comment]
[
![screenshot_20170416-080136](https://cloud.githubusercontent.com/assets/27584740/25071114/61bd662e-227d-11e7-921a-18b572d65300.png)
](url)

**Comment by Chiaramonte1981** [comment]
I added the picture and I added the section of log. Hope this helps

**Comment by nightflyer73** [comment]
I'm sorry but that's not enough. I need a complete verbose log file. You can post it to pastebin and link it here.

**Comment by Chiaramonte1981** [comment]
https://logs.tvaddons.ag/prcnxqvqj

**Comment by Chiaramonte1981** [comment]
I tried it on Kodi Jarvis and Krypton and spmc 16.3 and 16.6 for Android and same issues when opening  https://logs.tvaddons.ag/prcnxqvqj

**Comment by nightflyer73** [comment]
This bug is a duplicate of #22.
