### ISSUE TITLE
Non si avvia 

### ISSUE THREAD

**Issue by atrasatti** [nightflyer73/plugin.video.raitv#24]
Ho Kodi 17.1 e RAI on demand 2.0.0 scaricata dal repo ufficiale di Kodi. Da un paio di settimane l'add-on non si avvia. Ho provato sia su MacOS che Amazon fire tv.

Sono fuori dall'Italia, ma tanti programmi sono normalmente visibili su RAI.tv

**Comment by nightflyer73** [comment]
Duplicate of #22.
