### ISSUE TITLE
http error 403 in avvio plugin

### ISSUE THREAD

**Issue by manzolo** [nightflyer73/plugin.video.raitv#26]
Ciao,
Non conosco python, ma da ieri non funzionava più e ho fatto un breve debug e nel file 
plugin.video.raitv/resources/lib/rayplay.py
L'errore è un 403 sull'url:
http://mediapolisgs.rai.it/relinker/relinkerServlet.htm?cont=201342
<pre>
  File "/home/pi/.kodi/addons/plugin.video.raitv/default.py", line 429, in <module>
	log_country()
  File "/home/pi/.kodi/addons/plugin.video.raitv/default.py", line 354, in log_country
	country = raiplay.getCountry()
  File "/home/pi/.kodi/addons/plugin.video.raitv/resources/lib/raiplay.py", line 16, in getCountry
	response = urllib2.urlopen(self.localizeUrl).read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
	return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
	response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
	'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
	return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
	result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
	raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
</pre>
Ho notato che mettendo fisso "IT" che è la response dell'url incriminato è tornato a funzionare, ma non è ovviamente la soluzione... cosa può essere che da browser risponde e da pyhton ritorna 403?
<pre>
def getCountry(self):
        #response = urllib2.urlopen(self.localizeUrl).read()
        response = "IT"
        return response
</pre>

**Comment by gdx2015** [comment]
Secondo me è una questione di "user-agent", nell'addon è impostato quello predefinito cioè: "Python-urllib/2.7" e non uno di un browser per questo da errore 403 forbidden con Kodi

**Comment by nightflyer73** [comment]
Grazie gdx2015. Cerco di fare un update in settimana.

**Comment by strk** [comment]
Tornare "IT" dalla getCountry in effetti funziona, forse l'_init_ di relinker.py non e' sufficiente a configurare urllib2 in tempo per la chiamata a getCountry ?

**Comment by gdx2015** [comment]
il problema è in raiplay.py non in relinker.py. Puoi dare un'occhiata all'aggiunta, di cui parlavo sopra, che ho fatto da profano in raiplay.py  https://pastebin.com/s7uPmEwf .  Vedrai che funziona perfettamente.  Nella pagina http://mediapolisgs.rai.it/relinker/relinkerServlet.htm?cont=201342 dovrebbe leggere IT se vai col browser ma siccome come user-agent c'è quello predefinito  "Python-urllib/2.7" quella pagina restituisce Forbidden.

**Comment by thej4ck** [comment]
Confermo stesso problema.

**Comment by Testato** [comment]
allego log Win10

```
19:27:49.714 T:2852   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
19:27:50.371 T:4792   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 403: Forbidden
                                            Traceback (most recent call last):
                                              File "C:\Users\win10\AppData\Roaming\Kodi\addons\plugin.video.raitv\default.py", line 429, in <module>
                                                log_country()
                                              File "C:\Users\win10\AppData\Roaming\Kodi\addons\plugin.video.raitv\default.py", line 354, in log_country
                                                country = raiplay.getCountry()
                                              File "C:\Users\win10\AppData\Roaming\Kodi\addons\plugin.video.raitv\resources\lib\raiplay.py", line 16, in getCountry
                                                response = urllib2.urlopen(self.localizeUrl).read()
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 435, in open
                                                response = meth(req, response)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 548, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 473, in error
                                                return self._call_chain(*args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 556, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 403: Forbidden
                                            -->End of Python script error report<--
19:27:50.398 T:2852   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.raitv/?content_type=video
19:27:50.399 T:2852   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.raitv/?content_type=video) failed
```

**Comment by thej4ck** [comment]
confermo che la patch di gdx2015 risolve.
Le volpi della rai si sono messi a filtrare gli user agent...

**Comment by Testato** [comment]
@gdx2015 
thanks for the temporary fix, it work for me also.

But i see that your file https://pastebin.com/s7uPmEwf
is very different from this https://github.com/nightflyer73/plugin.video.raitv/blob/master/resources/lib/raiplay.py

Are you fixed an old version ?

**Comment by Testato** [comment]
Funzionano solo le Dirette,
tutte le altre funzioni danno errore

```
20:24:05.383 T:4648   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: list indices must be integers, not str
                                            Traceback (most recent call last):
                                              File "C:\Users\win10\AppData\Roaming\Kodi\addons\plugin.video.raitv\default.py", line 418, in <module>
                                                show_ondemand_programme(pathId)
                                              File "C:\Users\win10\AppData\Roaming\Kodi\addons\plugin.video.raitv\default.py", line 287, in show_ondemand_programme
                                                if programme["infoProg"]["tipologia"][0]["nome"] == "Film":
                                            TypeError: list indices must be integers, not str
                                            -->End of Python script error report<--
20:24:05.417 T:4340   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.raitv/?mode=ondemand&path_id=http%3a%2f%2fwww.rai.it%2fraiplay%2fprogrammi%2fmemex-iluoghidellascienza%2f%3fjson&sub_type=PLR%20programma%20Page
20:24:05.418 T:4340   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.raitv/?mode=ondemand&path_id=http%3a%2f%2fwww.rai.it%2fraiplay%2fprogrammi%2fmemex-iluoghidellascienza%2f%3fjson&sub_type=PLR%20programma%20Page) failed
```

**Comment by gdx2015** [comment]
It is not an old version. It is the version contained in the official Kodi repository http://mirrors.kodi.tv/addons/krypton/plugin.video.raitv/ . The fix works fine, not just for live stream

**Comment by Brianzo** [comment]
Unfortunately,  the gdx2015 fix does not work for me.  I am using LibreElec with Kodi 17.4.  I applied the fix, but still get the error (see the log below). 

> 12:34:52.417 T:4099192928   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
> 12:34:56.511 T:3574268832   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <class 'urllib2.HTTPError'>
>                                             Error Contents: HTTP Error 403: Forbidden
>                                             Traceback (most recent call last):
>                                               File "/storage/.kodi/addons/plugin.video.raitv/default.py", line 452, in <module>
>                                                 play(url, pathId)
>                                               File "/storage/.kodi/addons/plugin.video.raitv/default.py", line 142, in play
>                                                 url = relinker.getURL(url)
>                                               File "/storage/.kodi/addons/plugin.video.raitv/resources/lib/relinker.py", line 44, in getURL
>                                                 response = urllib2.urlopen(url)
>                                               File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
>                                               File "/usr/lib/python2.7/urllib2.py", line 435, in open
>                                               File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
>                                               File "/usr/lib/python2.7/urllib2.py", line 473, in error
>                                               File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>                                               File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
>                                             HTTPError: HTTP Error 403: Forbidden
>                                             -->End of Python script error report<--
> 12:34:56.662 T:4099192928   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.raitv/?url=http%3A%2F%2Fmediapolis.rai.it%2Frelinker%2FrelinkerServlet.htm%3Fcont%3D2606803&mode=play]
>

**Comment by Testato** [comment]
Come hai applicato il fix ? 
Se scarichi questo repo e lo modifichi non funziona (non so il perché, é normale ?)

Io ho fatto questo:
- disinstallato il plugin da kodi,
- installato dinuovo il plugin via kodi, quindi quello che non funziona.
- avviato una volta il plugin in modo che i file vengono creati (guardando nella cartella del plugin si nota che se non si avvia i file sono vuoti)
- cancellare tutti i file .pyc autocreatesi
- applicare il fix
- rilanciare il plugin, ora si autocreeranno dinuovo i .pyc ma con il fix applicato

**Comment by realtebo** [comment]
Ci sono novità per questo fix? E' utilissimo il tuo addon e vorremmo tutti averlo di nuovo funzionante.

**Comment by realtebo** [comment]
Thanks

**Comment by Testato** [comment]
@nightflyer73 
When this new version will be pushed to Kodi repository ?

**Comment by nightflyer73** [comment]
@Testato I have to make other changes before I can push another version to the Kodi repository.

**Comment by LuccoJ** [comment]
Is there an ETA for this?

**Comment by maaaatteo** [comment]
sono alla versione 2.0.0 e mi da ancora errore 403 wtf??

**Comment by Germano0** [comment]
@nightflyer73 quando verrà aggiornata la versione nel repository Kodi?

**Comment by strk** [comment]
Mi chiedevo lo stesso. Ho installato il plugin ieri sulla macchina di
un'amica. E' stato molto triste vedere l'errore del plugin.

Forse potresti rilasciare una "patch version" con soltanto la
risoluzione di questo errore, e tenere la prossima "minor release"
per le nuove feature ?
