### ISSUE TITLE
Sezione Videonotizie non funzionante

### ISSUE THREAD

**Issue by Gythion** [nightflyer73/plugin.video.raitv#32]
Non ve ne siete accorti?
[kodi.log](https://github.com/nightflyer73/plugin.video.raitv/files/1821536/kodi.log)

**Comment by nightflyer73** [comment]
Me ne sono accorto e ci sto lavorando. Purtroppo c'è un errore nei dati della RAI. Il PathID che viene restituito usando l'xsl "rai_tv-statistiche-raiplay-json" è, da un po' di tempo, errato. Si può non usare, ma in questo modo non si possono riprodurre i sottotitoli.

**Comment by Gythion** [comment]
E come si fa?
