### ISSUE TITLE
non sis collega su kodi in UK

### ISSUE THREAD

**Issue by ciccio2018** [nightflyer73/plugin.video.raitv#33]
Ho aggiornato il Repo, e pure il VPN. Su kodi non si connetta. Se invece scarico l’app per l’ipad ed uso il VPN funziona. Non so se e un guasto del Repo o la Rai che blocca tutto ciò che viene da Kodi.

**Comment by nightflyer73** [comment]
L'uso di questo plugin dall'estero non è supportato.
