### ISSUE TITLE
Problemi con dirette tv

### ISSUE THREAD

**Issue by nx-99** [nightflyer73/plugin.video.raitv#36]
Mi capita che le dirette tv smettano di funzionare in maniera causale.
Ad esempio rai 2 per tutta la durate delle olimpiadi invernali in Corea non ha funzionato ed ora è l'unica rete rai che riesco a vedere in diretta. mentre rai scuola che è sempre andata ora non parte più.
Succede anche a voi, con kodi 16 e ubuntu 16.04 ?

**Comment by nightflyer73** [comment]
La riproduzione di stream live e registrati è fatta direttamente da Kodi. L'addon non fa altro che passare la URL corrispondente all'applicazione.  Fatta questa doverosa premessa, al momento non ho problemi i vari live stream con Kodi 17/Fedora 27. Considera però che non è una funzionalità che uso spesso.

**Comment by nx-99** [comment]
Dopo varie prove credo che il colpevole sia la versione di curl installata (7.50.3), se l'aggiorno (curl-7.59.0) questo addon funziona, ma blocca altri addon video tipo dpaly e youtube.
