### ISSUE TITLE
Rai on Demand Non Funziona!?

### ISSUE THREAD

**Issue by larry77** [nightflyer73/plugin.video.raitv#38]
Salve,
E grazie per l'eccellente addon! Da circa un paio di settimane, ho problemi con rai on demand. Ha smesso di funzionare sia con Kodi 17.6 su android che con Kodi 17.1 su Linux.
Uso un VPN, ma non ho cambiato niente nella sua configurazione da mesi.
Sono l'unico ad avere problemi?
Grazie 1000

**Comment by nx-99** [comment]
Io con ubuntu riscontro problemi dovuti a curl.

**Comment by nightflyer73** [comment]
Quando si apre un bug report, bisognerebbe sempre:

- indicare i passi per riprodurre il bug
- caricare il file di log su un servizio come pastebin.com e indicarne la URL

Diversamente è difficile capire cosa non funziona ed eventualmente cercare di aggiustarlo.

**Inoltre, l'uso di VPN, smart DNS o altro per aggirare il geo blocking non sono supportati.**

**Comment by larry77** [comment]
Ciao,
Il bug si produce sia sotto Debian che sotto Android semplicemente cercando di far partire rai on demand cliccando sull'icona.
Al link

http://paste.debian.net/1037188/

Trovi il log di Debian.

**Comment by nightflyer73** [comment]
Mi sembra che tu non stia usando la versione in questo repository github.

**Comment by larry77** [comment]
Ho installato rai on demand cercandolo nei repository già presenti in Kodi. Come posso installare (anche sotto android) la versione di github?

**Comment by nightflyer73** [comment]
Duplicato di #26.

**Comment by larry77** [comment]
Se ho capito bene, il caso è chiuso per modo di dire: la versione di rai on demand scaricabile da kodi non riflette lo stato dell'addon su github e non funziona. A quanto pare (visto che non ho avuto risposta) non c'e' un modo semplice di installare la versione del repository.
E' prevista una via di uscita (tipo aggiornare l'addon nei repository standard di kodi) a breve?

**Comment by nightflyer73** [comment]
> Se ho capito bene, il caso è chiuso per modo di dire: la versione di rai on demand scaricabile da kodi non riflette lo stato dell'addon su github e non funziona. 

Su github condivido gli sviluppi sull'addon. Se qualcuno apre un bug qui, è perché ha un problema con il codice che si trova qui.

> A quanto pare (visto che non ho avuto risposta) non c'e' un modo semplice di installare la versione del repository.

Perdonami, ma questo non è un forum di assistenza su come funziona Kodi.

Cercando su kodi.wiki poi trovare:
https://kodi.wiki/view/Add-on_manager#How_to_install_from_a_ZIP_file

> E' prevista una via di uscita (tipo aggiornare l'addon nei repository standard di kodi) a breve?

Questo addon è sviluppato nel mio tempo libero, che è sempre molto poco. Quindi, quando troverò il tempo, finirò le modifiche che sto facendo per avere un primo supporto a raiplayradio e poi farò una PR nel repository ufficiale.

**Comment by ZzedRaspberryItaly** [comment]
Buongiorno, segnalo che la RAI ha introdotto un sistema di account per poter fruire di alcuni contenuti http://www.rai.it/account/Faq-RaiPlay-3dd2e17c-0435-48db-968c-6a6d13d8e16b.html?s=ContentSet-e6111a90-7d03-414c-8636-82438aa33eee&i=ContentItem-50f00c37-451a-4a89-95ac-e9423f9bb316
Essendo l'addon precedente a tale situazione, naturalmente non supporta la gestione delle credenziali di accesso, e quei contenuti che richiedono registrazione, non vengono avviati.

**Comment by nightflyer73** [comment]
Mi puoi fare un esempio di contenuto non accessibile da addon?

**Comment by LorenzoRogai** [comment]
Il nome della rosa (la serie)
