### ISSUE TITLE
This Add-On is marked as Broken

### ISSUE THREAD

**Issue by DrSlump69** [nightflyer73/plugin.video.raitv#40]
Hi! I was done with watching a cartoon when Kodi told me that the plugin was not working, and it was uninstalled from my environment! I tried to install it again but it didn't show on the video plugin list (Rai YoYo is still there). Looking for information I stumbled upon this page https://kodi.tv/addon/music-add-ons-plugins-video-add-ons/rai-demand where it says "This Add-On is marked as Broken. This add-on is no longer function correctly and not maintained by it's developer.". From my experience the plugin is working ok, I use it everyday... What happened? I will try to install as zip, hoping Kodi will not uninstall it again.

Edit: ok, installing as zip works and kodi doesn't uninstall it anymore. Thanks

**Comment by nightflyer73** [comment]
It's because of this commit:
https://github.com/xbmc/repo-plugins/commit/98bf99a3b7df0acd69b1d13e294bc399ce52f87a

I have nothing to do with it. Sorry.

**Comment by miketyson666** [comment]
Nightflyer, sorry, forget the previous message. I confirm re-installing from zip file the plugin works (on Kodi 18 default.py and /resources/lib/raiplay.py should be replaced with the mod version).

**Comment by nightflyer73** [comment]
AFAIK ondemand streams work fine with this repository version of the addon. Are you located abroad?

Anyway, if you have issues, please open a new bug and provide:

- Kodi verision used
- addon version used
- steps to reproduce the bug
- upload the log file to pastebin.com or similar service

**Comment by miketyson666** [comment]
On Kodi 18 (on Ubuntu) I should use this modification in default.py:
def addLinkItem(parameters, li, url=""):
    if url == "":
        url = sys.argv[0] + '?' + urllib.urlencode(parameters)
    li.setProperty('IsPlayable', 'true')
    li.setInfo("video", {})
    return xbmcplugin.addDirectoryItem(handle=handle, url=url, 
        listitem=li, isFolder=False)
Without it doesn't work correctly.

**Comment by nightflyer73** [comment]
Currently I don't have a Kodi 18 installation but it's not clear to me what is not working.

There is already a call to liStyle.setInfo before every addLinkItem. Please note that not all content are videos there are also audio files.

**Comment by miketyson666** [comment]
You are right but my was a workaround to force the content to video, without it, the video are not played. I'm sure there is a more elegant solution that allows to play audio too, but sorry I'm a newbie on pyton and Kodi programming.

**Comment by nightflyer73** [comment]
There is no need to force the content to video. It's already properly implemented in the addon version in this git repo. If not, please open a new bug report filling in:

- Kodi verision used
- addon version used
- steps to reproduce the bug
- upload the log file to pastebin.com or similar service

**Comment by miketyson666** [comment]
Dear nightflyer, turned out my .zip file was not updated. Getting the latest version from github the problem with Video content disappeared. My fault.

**Comment by Testato** [comment]
I can confirm that this addon work without problem
