### ISSUE TITLE
Impossibile riprodurre contenuti

### ISSUE THREAD

**Issue by avalloneandrea** [nightflyer73/plugin.video.raitv#43]
Da alcuni giorni il plugin non funziona più: alla selezione di qualsiasi contenuto (Diretta o Replay che sia), non succede nulla e non viene riprodotto nulla.

Il log non mi sembra molto utile, questa è l'unica linea di errore che contiene, insieme ad alcuni warning:
`10:03:09.517 T:1939034128   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
10:03:33.899 T:1939034128 WARNING: Playlist Player: ListItem type must be audio or video, use ListItem::setInfo to specify!
10:04:45.451 T:1494713200 WARNING: Previous line repeats 1 times.
10:04:45.452 T:1494713200 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
10:04:45.523 T:1494713200 WARNING: Previous line repeats 2 times.
10:04:45.523 T:1494713200  NOTICE: LoadJpeg: unable to load http://www.rai.it/resizegd/256x-/dl/img/2018/01/11/1515668736162_sottovoce.jpg
10:04:45.561 T:1709937520 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
10:04:45.561 T:1709937520  NOTICE: LoadJpeg: unable to load http://www.rai.it/resizegd/256x-/dl/img/2017/09/11/1505142966393_unomattina_2017_2048x1152.jpg
10:04:45.569 T:1486320496 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
10:04:45.569 T:1486320496  NOTICE: LoadJpeg: unable to load http://www.rai.it/resizegd/256x-/dl/img/2018/08/01/1533130877623_l-estate-del-mio-primo-bacio_2048x1152.jpg
10:04:45.576 T:1503105904 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
10:04:45.577 T:1503105904  NOTICE: LoadJpeg: unable to load http://www.rai.it/resizegd/256x-/dl/img/2018/08/31/1535727003883_2048x1152.jpg`

Sto usando LibreELEC 8.90.005 con Kodi 18.0b2 di Kodi su Raspberry Pi 2B.
La versione del plugin è la 2.0.0.

**Comment by nightflyer73** [comment]
Il log non è completo, mancano delle informazioni. La versione che stai usando è l'ultima presente in questo repository?

**Comment by avalloneandrea** [comment]
Stavo usando l'ultima versione (2.0.0) del tuo plugin, che ho scaricato da un altro repository che avevo configurato su Kodi.
Come suggerito, ho disinstallato quella versione e installato l'ultima versione (sempre 2.0.0) scaricata direttamente qui da github, e il plugin è tornato a funzionare.
La versione è la stessa, quindi mi sembra abbastanza strano, ma l'importante è che adesso è tutto risolto! Grazie e scusa per il disturbo :)
