### ISSUE TITLE
Addon rimosso dal repo ufficiale

### ISSUE THREAD

**Issue by Testato** [nightflyer73/plugin.video.raitv#44]
Oggi cercavo di installarlo dal repo ufficiale, ma non lo trovavo.
Cercanfo sul wiki kodi leggo che è stato deprecato ?

https://kodi.wiki/view/Add-on:Rai_On_Demand

**Comment by nightflyer73** [comment]
Duplicato di #40.

**Comment by Testato** [comment]
Ho scritto sul commit incriminato.
Tu lo hai fatto presente ?

**Comment by Testato** [comment]
Ha risposto il tipo di Kodi, dice che non hai aggiornato la versione sul loro repo.
Effettivamente è così, anche io ho un addon sul repo ufficiale, non c'è un automatismo, quando si pubblica su github nuiva versione poi si deve pubblicare ancge sul repo kodi

**Comment by nightflyer73** [comment]
Lo so che non c'è un automatismo (e che non ho ancora avuto il tempo di fare un push della versione in questo repository). Ma la versione che era presente nel repo ufficiale, seppur non aggiornata, funzionava ancora.
